---
################################################
## Packages / Weather
################################################

homeassistant:
  customize:

    ################################################
    ## Node Anchors
    ################################################

    package.node_anchors:
      customize: &customize
        package: 'weather'

      expose: &expose
        <<: *customize
        haaska_hidden: false
        homebridge_hidden: false

    ################################################
    ## Sensor
    ################################################

    sensor.buienradar_precipitation_forecast_average:
      <<: *customize
      friendly_name: Verwachte gemiddelde neerslag
      unit_of_measurement: 'mm/u'

################################################
## Sensor
################################################

sensor:
  - platform: buienradar
    latitude: !secret homeassistant_latitude
    longitude: !secret homeassistant_longitude
    timeframe: 60
    monitored_conditions:
      - precipitation_forecast_average
      - symbol
      - humidity
      - temperature
      - windspeed
      - groundtemperature
      - precipitation

  # Darksky
  - platform: darksky
    api_key: !secret darksky_api
    forecast:
      - 0
      - 1
      - 2
      - 3
      - 4
      - 5
    monitored_conditions:
      - icon
      - summary
      - nearest_storm_distance
      - nearest_storm_bearing
      - humidity
      - temperature
      - temperature_high
      - temperature_low
      - apparent_temperature
      - apparent_temperature_high
      - apparent_temperature_low
      - wind_speed
      - wind_bearing
      - precip_type
      - precip_probability
      - precip_accumulation
      - precip_intensity
      - precip_intensity_max
      - uv_index
      - daily_summary
      - pressure
      - visibility
    scan_interval:
      minutes: 5

################################################
## Weather Darksky component
################################################
weather:
  - platform: darksky
    api_key: !secret darksky_api
    mode: daily

