---
################################################
## Packages / Weather
################################################

homeassistant:
  customize:

    ################################################
    ## Node Anchors
    ################################################

    package.node_anchors:
      customize: &customize
        package: 'weather'

      expose: &expose
        <<: *customize
        haaska_hidden: false
        homebridge_hidden: false

    ################################################
    ## Sensor
    ################################################

    sensor.buienradar_precipitation_forecast_average:
      <<: *customize
      friendly_name: Verwachte gemiddelde neerslag
      unit_of_measurement: 'mm/u'

################################################
## Sensor
################################################

sensor:
  - platform: buienradar
    latitude: !secret homeassistant_latitude
    longitude: !secret homeassistant_longitude
    timeframe: 60
    monitored_conditions:
      - precipitation_forecast_average
      - symbol
      - humidity
      - temperature
      - windspeed
      - groundtemperature
      - precipitation

  # Darksky
  - platform: darksky
    api_key: !secret darksky_api
    forecast:
      - 0
      - 1
      - 2
      - 3
      - 4
      - 5
    monitored_conditions:
      - icon
      - summary
      - nearest_storm_distance
      - nearest_storm_bearing
      - humidity
      - temperature
      - temperature_high
      - temperature_low
      - apparent_temperature
      - apparent_temperature_high
      - apparent_temperature_low
      - wind_speed
      - wind_bearing
      - precip_type
      - precip_probability
      - precip_accumulation
      - precip_intensity
      - precip_intensity_max
      - uv_index
      - daily_summary
      - pressure
      - visibility
    scan_interval:
      minutes: 5

################################################
## Weather Darksky component
################################################
weather:
  - platform: darksky
    api_key: !secret darksky_api
    mode: daily

################################################
## Group
################################################
group:
  darksky_sensors:
    name: Darksky sensoren
    entities:
      - sensor.dark_sky_apparent_temperature
      - sensor.dark_sky_daily_max_precip_intensity_0
      - sensor.dark_sky_daily_max_precip_intensity_1
      - sensor.dark_sky_daily_max_precip_intensity_2
      - sensor.dark_sky_daily_max_precip_intensity_3
      - sensor.dark_sky_daily_max_precip_intensity_4
      - sensor.dark_sky_daily_max_precip_intensity_5
      - sensor.dark_sky_daily_summary
      - sensor.dark_sky_daytime_high_apparent_temperature_0
      - sensor.dark_sky_daytime_high_apparent_temperature_1
      - sensor.dark_sky_daytime_high_apparent_temperature_2
      - sensor.dark_sky_daytime_high_apparent_temperature_3
      - sensor.dark_sky_daytime_high_apparent_temperature_4
      - sensor.dark_sky_daytime_high_apparent_temperature_5
      - sensor.dark_sky_daytime_high_temperature_0
      - sensor.dark_sky_daytime_high_temperature_1
      - sensor.dark_sky_daytime_high_temperature_2
      - sensor.dark_sky_daytime_high_temperature_3
      - sensor.dark_sky_daytime_high_temperature_4
      - sensor.dark_sky_daytime_high_temperature_5
      - sensor.dark_sky_humidity
      - sensor.dark_sky_humidity_0
      - sensor.dark_sky_humidity_1
      - sensor.dark_sky_humidity_2
      - sensor.dark_sky_humidity_3
      - sensor.dark_sky_humidity_4
      - sensor.dark_sky_humidity_5
      - sensor.dark_sky_icon
      - sensor.dark_sky_icon_0
      - sensor.dark_sky_icon_1
      - sensor.dark_sky_icon_2
      - sensor.dark_sky_icon_3
      - sensor.dark_sky_icon_4
      - sensor.dark_sky_icon_5
      - sensor.dark_sky_nearest_storm_bearing
      - sensor.dark_sky_nearest_storm_distance
      - sensor.dark_sky_overnight_low_apparent_temperature_0
      - sensor.dark_sky_overnight_low_apparent_temperature_1
      - sensor.dark_sky_overnight_low_apparent_temperature_2
      - sensor.dark_sky_overnight_low_apparent_temperature_3
      - sensor.dark_sky_overnight_low_apparent_temperature_4
      - sensor.dark_sky_overnight_low_apparent_temperature_5
      - sensor.dark_sky_overnight_low_temperature_0
      - sensor.dark_sky_overnight_low_temperature_1
      - sensor.dark_sky_overnight_low_temperature_2
      - sensor.dark_sky_overnight_low_temperature_3
      - sensor.dark_sky_overnight_low_temperature_4
      - sensor.dark_sky_overnight_low_temperature_5
      - sensor.dark_sky_precip
      - sensor.dark_sky_precip_0
      - sensor.dark_sky_precip_1
      - sensor.dark_sky_precip_2
      - sensor.dark_sky_precip_3
      - sensor.dark_sky_precip_4
      - sensor.dark_sky_precip_5
      - sensor.dark_sky_precip_accumulation_0
      - sensor.dark_sky_precip_accumulation_1
      - sensor.dark_sky_precip_accumulation_2
      - sensor.dark_sky_precip_accumulation_3
      - sensor.dark_sky_precip_accumulation_4
      - sensor.dark_sky_precip_accumulation_5
      - sensor.dark_sky_precip_intensity
      - sensor.dark_sky_precip_intensity_0
      - sensor.dark_sky_precip_intensity_1
      - sensor.dark_sky_precip_intensity_2
      - sensor.dark_sky_precip_intensity_3
      - sensor.dark_sky_precip_intensity_4
      - sensor.dark_sky_precip_intensity_5
      - sensor.dark_sky_precip_probability
      - sensor.dark_sky_precip_probability_0
      - sensor.dark_sky_precip_probability_1
      - sensor.dark_sky_precip_probability_2
      - sensor.dark_sky_precip_probability_3
      - sensor.dark_sky_precip_probability_4
      - sensor.dark_sky_precip_probability_5
      - sensor.dark_sky_pressure
      - sensor.dark_sky_pressure_0
      - sensor.dark_sky_pressure_1
      - sensor.dark_sky_pressure_2
      - sensor.dark_sky_pressure_3
      - sensor.dark_sky_pressure_4
      - sensor.dark_sky_pressure_5
      - sensor.dark_sky_summary
      - sensor.dark_sky_summary_0
      - sensor.dark_sky_summary_1
      - sensor.dark_sky_summary_2
      - sensor.dark_sky_summary_3
      - sensor.dark_sky_summary_4
      - sensor.dark_sky_summary_5
      - sensor.dark_sky_temperature
      - sensor.dark_sky_uv_index
      - sensor.dark_sky_uv_index_0
      - sensor.dark_sky_uv_index_1
      - sensor.dark_sky_uv_index_2
      - sensor.dark_sky_uv_index_3
      - sensor.dark_sky_uv_index_4
      - sensor.dark_sky_uv_index_5
      - sensor.dark_sky_visibility
      - sensor.dark_sky_visibility_0
      - sensor.dark_sky_visibility_1
      - sensor.dark_sky_visibility_2
      - sensor.dark_sky_visibility_3
      - sensor.dark_sky_visibility_4
      - sensor.dark_sky_visibility_5
      - sensor.dark_sky_wind_bearing
      - sensor.dark_sky_wind_bearing_0
      - sensor.dark_sky_wind_bearing_1
      - sensor.dark_sky_wind_bearing_2
      - sensor.dark_sky_wind_bearing_3
      - sensor.dark_sky_wind_bearing_4
      - sensor.dark_sky_wind_bearing_5
      - sensor.dark_sky_wind_speed
      - sensor.dark_sky_wind_speed_0
      - sensor.dark_sky_wind_speed_1
      - sensor.dark_sky_wind_speed_2
      - sensor.dark_sky_wind_speed_3
      - sensor.dark_sky_wind_speed_4
      - sensor.dark_sky_wind_speed_5
