---
# Give a notification if there is a beta update, but not equal to that of the stable.
- alias: Notify - Beta version
  initial_state: true
  trigger:
    - platform: state
      entity_id: sensor.hassio_beta_versie
  condition:
    - condition: template
      value_template: "{{ states.sensor.hassio_stable_versie.state != states.sensor.hassio_beta_versie.state }}"
  action:
    - service: notify.telegram_klaas
      data:
        message: 'Beta update beschikbaar voor Home Assistant, versie: {{ states.sensor.hassio_beta_versie.state }}'
