---
# Give a notification if there is a stable update.
- alias: Notify - Stable version
  initial_state: true
  trigger:
    - platform: state
      entity_id: sensor.hassio_stable_versie
  action:
    - service: notify.telegram_klaas
      data_template:
        title: Upgrade time!
        message: >-
          'Er is een nieuwe stable versie voor Hass.io!'
          'Versie: {{ states('sensor.hassio_stable_versie') }} is zojuist gereleased.'
