---
#
# Github template sensors
# Through these sensors I read how many stars my github config has and what the last commit message was
#
- platform: template
  sensors:
    github_config_stars:
      value_template: "{{ state_attr('sensor.smarthome_homeassistant_config','stargazers') }}"
      friendly_name: "Aantal sterren op Github config"
      unit_of_measurement: Stars
      icon_template: mdi:star

- platform: template
  sensors:
    github_commit_message:
      value_template: "{{ state_attr('sensor.smarthome_homeassistant_config','latest_commit_message') }}"
      friendly_name: "Laatste commit bericht"
